export const CURRENCY_LIST_REQUEST = "CURRENCY_LIST_REQUEST";
export const CURRENCY_LIST_SUCCESS = "CURRENCY_LIST_SUCCESS";
export const CURRENCY_LIST_FAIL = "CURRENCY_LIST_FAIL";

export const CURRENCY_DETAILS_REQUEST = "CURRENCY_DETAILS_REQUEST";
export const CURRENCY_DETAILS_SUCCESS = "CURRENCY_DETAILS_SUCCESS";
export const CURRENCY_DETAILS_FAIL = "CURRENCY_DETAILS_FAIL";

export const CURRENCY_DATA_REQUEST = "CURRENCY_DATA_REQUEST";
export const CURRENCY_DATA_SUCCESS = "CURRENCY_DATA_SUCCESS";
export const CURRENCY_DATA_CLEAR = "CURRENCY_DATA_CLEAR";
export const CURRENCY_DATA_FAIL = "CURRENCY_DATA_FAIL";

export const SEARCH_CURRENCY = "SEARCH_CURRENCY";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
